name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build with Maven
      run: |
        cd frontend
        mvn clean package
        
    - name: Deploy to Heroku
      if: github.ref == 'refs/heads/main'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku container:push web --app $HEROKU_APP_NAME
        heroku container:release web --app $HEROKU_APP_NAME 